# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Gist' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'

  # Pods for Gist

  target 'GistTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GistUITests' do
    # Pods for testing
  end

end
